export const data=[
    {
        source:"about1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    },
    {
        source:"./pictures/summer1.jpg"
    }
]
   